Version: v2
Decription: FOSS list
LastUpdate: 2024-01-18 12:28
FOSS:
    # Available in Bazaar
    FOSSName: swagger-core
    # Available in Bazaar
    FOSSVersion: 1.6.12
    # Available in Bazaar >>> used as kind of ID.
    FOSSURL: https://github.com/swagger-api/swagger-core/archive/v{{FOSSVersion}}.tar.gz
    # Available in Bazaar
    PRIMNumber(CAX/CTX): 71/CAX1056692
    # Not Available in Bazaar
    Primary: N
    # Available in Bazaar
    STAKOCode: General use
    # Available in Bazaar
    STAKOReason: NA
    # Not Available in Bazaar    
    FunctionalityUsedInTheEricssonProduct: Examples and server integrations for generating the Swagger API Specification, which enables easy access to your REST API
    # Available in Bazaar. Not used for specific report. >>> Includes _list_ of licenses taken from Bazaar
    AvailableLicenses: Apache License 2.0
    # Not available in Bazaar, >>> FAL should be factored out into separate mapping file
    ChoiceOfLicense: Apache License 2.0
    # Not Available in Bazaar >>> list of algorithms used (instead of bool)
    CryptographicAlgorithmsUsed: ()
    # Not Available in Bazaar
    CryptographicAlgorithmsUsedDescription: NA
    # Not Available in Bazaar >>> list
    SecureProtocolsUsed: ()
    # Not Available in Bazaar
    SecureProtocolsUsedDescription: NA
    # Select one of the following: Statically, Dynamically, Classpath, NotLinked. Not Available in Bazaar
    EricssonCodeLinkedWithTheFOSSCode: Dynamically
    # Not Available in Bazaar
    MavenDependency: 
    - 'io.swagger:swagger-annotations:jar:{{FOSSVersion}}'
    - 'io.swagger:swagger-core:jar:{{FOSSVersion}}'
    - 'io.swagger:swagger-models:jar:{{FOSSVersion}}'
    # >>> New attribute:
    # If yes, the default values of /scripts/fossReport/templates/defaultTemplate.yaml are not taken into account.
    # In this case, the yaml attributes of the defaultTemplate.yaml should be copied in this file with the desired values.
    ManualSpecificFOSSEvaluation: NO
    ReportAuthor: XEIRPAP Eirini Papastefanaki
