apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "eric-sc-hcagent.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "eric-sc-hcagent.labels" . | indent 4 }}
    app: {{ template "eric-sc-hcagent.name" . }}
  annotations:
{{- include "eric-sc-hcagent.helm-annotations" . | indent 4 }}
{{- include "eric-sc-hcagent.config-annotations" . | indent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - pods
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["apps"]
    resources:
      - statefulsets
      - replicasets
      - deployments
    verbs:
      - get
      - list
  - apiGroups: ["batch"]
    resources:
      - cronjobs
      - jobs
    verbs:
      - get
      - list