apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "eric-sc-hcagent.name" . }}
  labels:
{{- include "eric-sc-hcagent.labels" . | indent 4 }}
    app: {{ template "eric-sc-hcagent.name" . }}
  annotations:
{{- include "eric-sc-hcagent.helm-annotations" . | indent 4 }}
{{- include "eric-sc-hcagent.config-annotations" . | indent 4 }}
  namespace: {{ .Release.Namespace }}